### PR TITLE
@gndclouds/community v2

### LINKED ISSUE #355: Community: Fix these borders before we launch
Screen Shot 2020-10-05 at 9 44 57 AM

https://filecoin.onrender.com/community

### PR DESCRIPTION
**Pull request by gndclouds**
Fixed #355 and fixed button cursor.

### CODE REVIEW

**Comment by gndclouds** [comment]
Fixing conflicts one sec

**Comment by jimmylee** [comment]
Put a WIP tag on it if you are not ready to land

**Comment by gndclouds** [comment]
I know that, I just found out though @tarafanlin that @harisbutt has more notes. But I'm waiting to hear what they are. So I thought the page was done. Other wise I will add WIP 😉

**Comment by gndclouds** [comment]
Ready for review @jimmylee

**Review by jimmylee — APPROVED** [review]
LGTM, will merge to test

**Pull request merged**
