### PR TITLE
Update: Moved UnityFrame from Canvas to Iframe #432

### PR DESCRIPTION
**Pull request by Aminejvm**
This PR fixes all the keyboard input related bugs

### CODE REVIEW

**Comment by jimmylee** [comment]
I am not sure I am happy with the move to the iFrame, great work @Aminejvm getting us to this point for discussion, @martinalong maybe we could explore for some slate objects what it looks like when they don't have the input fields? Since clicking will still work.

**Comment by martinalong** [comment]
Yeah we can make it so the input fields are hidden for specific cases. Are each of these unity games of a the same file type? e.g. "application/pdf" or "application/unitygame". (or is there some other way to identify them?) If so we can check for that type and hide the sidebar with the inputs in those cases pretty easily.

**Comment by jimmylee** [comment]
They will always be "application/unity" IIRC

**Comment by Aminejvm** [comment]
Yes if we can hide inputs on this case3, we can definitely keep the current implementation, I just need to update the cleanup function to remove the unity script

**Pull request closed without merging**
