### PR TITLE
@tarafanlin/new landing

### PR DESCRIPTION
**Pull request by tarafanlin**
WIP Update on:
landing page
slate for chrome

┆Issue is synchronized with this [Notion page](https://www.notion.so/tarafanlin-new-landing-7070f0c06fd847b3918a7618b9d79cb2) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by martinalong** [comment]
I'd recommend going to your terminal when you first run "npm run dev" on this branch and addressing the errors that it raises
image
image
^for stuff like this, the reason is b/c react doesn't use the same naming as html. html uses stuff like fill-rule, while react converts it to camelcase e.g. fillRule

**Comment by martinalong** [comment]
The border of the input here is really faint 
image

**Comment by martinalong** [comment]
image
Don't forget to swap these out for the actual logos later

**Comment by tarafanlin** [comment]
> I'd recommend going to your terminal when you first run "npm run dev" on this branch and addressing the errors that it raises image image ^for stuff like this, the reason is b/c react doesn't use the same naming as html. html uses stuff like fill-rule, while react converts it to camelcase e.g. fillRule

I see thanks!

**Comment by tarafanlin** [comment]
> image Don't forget to swap these out for the actual logos later

yeah I have it in the to do list.

**Comment by tarafanlin** [comment]
> The border of the input here is really faint image

for this one it's more of a placeholder for now. 
Amine is going to help connecting the auth, 
so it's up to him how he wants to construct the component.

**Pull request merged**
