### PR TITLE
minor fixes for the data scene

### PR DESCRIPTION
**Pull request by tarafanlin**
- remove "usage"
- fix file title overflow
Screen Shot 2020-10-21 at 9 58 21 PM

### CODE REVIEW

**Comment by jimmylee** [comment]
Way to jump on this :) I'm not sure this fixes text-overflow though? Do you have a screenshot of the solution?

**Comment by tarafanlin** [comment]
> Way to jump on this :) I'm not sure this fixes text-overflow though? Do you have a screenshot of the solution?

yep see the first file:
Screen Shot 2020-10-21 at 10 35 39 PM

**Comment by jimmylee** [comment]
I suppose this solution works, Its better than what we have now, but its still better to use `flex-shrink: 0` anchor elements and then a min-width: 10% (for safari), width: 100%; and text-overflow: ellipsis

**Comment by tarafanlin** [comment]
> I suppose this solution works, Its better than what we have now, but its still better to use `flex-shrink: 0` anchor elements and then a min-width: 10% (for safari), width: 100%; and text-overflow: ellipsis

ah ok, I can try this approach when I update the data table design

**Pull request merged**
